# Maximum width of each line
max_width = 100

# Number of spaces per tab
tab_spaces = 4

# Reorder imports alphabetically
reorder_imports = true

# Where to place item attributes
fn_args_layout = "compressed"

# Control the layout of match arms
match_arm_blocks = true

# How to format closure arguments
wrap_comments = true

# Format code blocks in documentation
format_code_in_doc_comments = true

# Format strings in documentation
format_strings = true

# How to format arrays
array_width = 100

# Format numeric literals
use_small_heuristics = "Default"

# Controls the maximum width for string literals
max_width = 100

# Place a trailing comma whenever multiline arrays and function arguments would span more than one line
trailing_comma = "Vertical"

# Whether to merge multiple derives into a single one if possible
merge_derives = true

# Format template-style strings in strings
format_macro_matchers = true

# Whether to add space after the match keyword
match_block_trailing_comma = false

# Whether to add space after the for keyword
spaces_around_ranges = false