# Maximum width of each line
max_width = 100

# Number of spaces per tab
tab_spaces = 4

# Reorder imports alphabetically
reorder_imports = true

# How to format arrays
array_width = 100

# Format numeric literals
use_small_heuristics = "Default"

# Whether to merge multiple derives into a single one if possible
merge_derives = true
