blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/thomasvincent/commitkit-rust/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/thomasvincent/commitkit-rust/blob/main/README.md
    about: Check the documentation for usage information.